exclude: '^$'
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    sha: v0.20.0
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
