# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(help_text='Journey title', max_length=128)),
                ('description',
                 models.TextField(help_text='Session details',
                                  max_length=512)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
